# ----
# Site

title: Tasty Recipes 247
url: "http://tastyrecipes247.com/"
baseurl:
google_analytics_key:
#  TODO - to add
newsletter_action:
disqus_shortname: tastyrecipes247

# Values for the jekyll-seo-tag gem (https://github.com/jekyll/jekyll-seo-tag)
logo: /siteicon.png
description: Food blog template for Jekyll.
author:
  name: Tasty Recipes 247
  email: pratibha.recipes247@gmail.com
  twitter: tastyrecipes247
social:
  name: Tasty Recipes 247
  links:
    - https://github.com/CloudCannon/treat-jekyll-template

# -----
# Build

timezone: Etc/UTC

paginate: 10
paginate_path: "/:num/"
permalink: pretty

defaults:
  - scope:
      path: "images"
    values:
      image: true

  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      push_sidebar_down: true
      print_stylesheet: true
      comments: true
      _options:
        content:
          width: 1560
          height: 2000
        featured_image:
          width: 1560
          height: 2000
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: "index.html"
    values:
      layout: "default"
      push_sidebar_down: true

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-paginate

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENCE

# -----------
# CloudCannon

social_icons:
  - Facebook
  - Google Plus
  - Instagram
  - LinkedIn
  - Pinterest
  - Tumblr
  - Twitter
  - YouTube
  - RSS

_options:
  author_image:
    width: 400
    height: 400
