# ----
# Site

title: Tasty Recipes 247
tagline: A blog dedicated to easy cooking & Indian Recipes
url: "http://tastyrecipes247.com/"
baseurl:
google_analytics_key: G-24T56CNX85
#  TODO - to add
newsletter_action: https://tastyrecipes247.us1.list-manage.com/subscribe/post?u=0ae66407fe629b85b2020cbd3&amp;id=21f0e49f0e
disqus_shortname: tastyrecipes247

# Values for the jekyll-seo-tag gem (https://github.com/jekyll/jekyll-seo-tag)
logo: /siteicon.png
description: This is a food blog for Indian recipes & Indian cooking at home. All of the recipes here are very easy, tasty and perfect for beginners. All recipes are also there on Youtube Channel Tasty Recipes 247.

author:
  name: Tasty Recipes 247
  email: pratibha.recipes247@gmail.com
  twitter: tastyrecipes247
social:
  name: Tasty Recipes 247
  links:
    - https://www.instagram.com/tastyrecipes247
    - https://www.facebook.com/tastyrecipes247
    - https://twitter.com/tastyrecipes247

# -----
# Build

timezone: Etc/UTC

paginate: 10
paginate_path: "/:num/"
permalink: pretty

defaults:
  - scope:
      path: "images"
    values:
      image: true

  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      push_sidebar_down: true
      print_stylesheet: true
      comments: true
      _options:
        content:
          width: 1560
          height: 2000
        featured_image:
          width: 1560
          height: 2000
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: "index.html"
    values:
      layout: "default"
      push_sidebar_down: true

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-paginate

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENCE

# -----------
# CloudCannon
locale: en_IN
social_icons:
  - Facebook
  - Google Plus
  - Instagram
  - LinkedIn
  - Pinterest
  - Tumblr
  - Twitter
  - YouTube
  - RSS

_options:
  author_image:
    width: 400
    height: 400
